# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: &development
  adapter: mysql
  encoding: utf8
  reconnect: false
  #database: quizzilla_development
  database: questness_development_s8
  pool: 5
  username: root
  password: root
  # JRuby doesn't support # JRuby doesn't support socket:
                          #socket:
  host: 127.0.0.1
  ## JRuby doesn't support socket:
  #socket: /tmp/mysql.sock

jruby:
  adapter: jdbcmysql
  encoding: utf8
  reconnect: false
  #database: quizzilla_development
  database: questness_development_s8
  pool: 5
  username: gmc
  password:
  # JRuby doesn't support # JRuby doesn't support socket:
                          #socket:
  host: 127.0.0.1
  ## JRuby doesn't support socket:
  #socket: /tmp/mysql.sock

simulation:
  adapter: mysql
  encoding: utf8
  reconnect: false
  #database: quizzilla_development
  database: questness_development_s8
  pool: 5
  username: gmc
  password:
  # JRuby doesn't support # JRuby doesn't support socket:
                          #socket:
  host: 127.0.0.1


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: questness_test
  pool: 5
  username: gmc
  password:
  # JRuby doesn't support # JRuby doesn't support socket:
                          #socket:
  host: 127.0.0.1
  ## JRuby doesn't support socket:
   #socket: /tmp/mysql.sock

staging:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: questness_production_s9
  pool: 5
  username: root
  password: root

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: questness_production_s8
  pool: 5
  username: root
  password: maxwell123
  # JRuby doesn't support # JRuby doesn't support socket:
                          #socket:
#  host: db_primary
  ## JRuby doesn't support socket:
   #socket: /tmp/mysql.sock
